server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: breadcrumb

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

breadcrumb:
  ingest-api-key: ${INGEST_API_KEY:local-development-key}